---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# codemogAPI R Package

NOTE: This package and the APIs that it wraps are in constant development right now.  This package should not be used for any actual data work as the API server isn't currently at a stable URL. This note will be removed when this is finished and the version number bumped to 0.1.1 from 0.1.0.

The `codemogAPI` package is built as the R interface to the Colorado State Demography Office data API set. 

Eventually, this package will allow the use to pull any of the State Demography Office data for Colorado and most geographies in the U.S. and tables from the American Community Survey 2012, 2013, and 2014 5-year Files and the 1980, 1990, 2000, and 2010 Decennial Census'.  A list of currently included data is below.

Currently Included Data:

* County Population estimates from 2010 to 2014 for Colorado Counties (see vignette "Accessing Population Data")
* Municipal Populations estimates from 2010 to 2014 in total or divided up into county specific parts. (see vignette "Accessing Population Data")


## Installation

* From GitHub (currently the only method)

```R
if (packageVersion("devtools") < 1.6) {
      install.packages("devtools")
    }
    devtools::install_github("ColoradoDemography/codemogAPI")
```


